# config
email: chenxj1993@gmail.com
address: ShangHai

cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: 每一个不曾起舞的日子都是对生命的辜负。

# Miscellaneous
github: https://github.com/chenxjGit
twitter: https://twitter.com/
facebook: https://www.facebook.com/people/Xj-Chen/100011691840447
weibo: http://weibo.com/u/2982623570
zhihu: http://www.zhihu.com/people/maybezh/
douban: https://www.douban.com/people/148676163/
instagram: https://www.instagram.com/maybe_ins/
google: https://google.com/
baidu: http://www.baidu.com/

# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#duoshuo name
duoshuo: maybeds

#Links
links:
- name: ChenXj
  link: http://chenxjGit.github.io/
  description: 我的Github
- name: TKL(Hexo Theme)
  link: https://github.com/chenxjGit/TKL
  description: Blog主题

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-Latest
- num: 4
  word: More